- Numpy array are mutable.
- NumPy arrays do not typically allow a mixture of different data types within a single array. NumPy arrays are designed to be homogeneous, meaning all elements within a given array must be of the same data type. This is a key difference from Python lists, which can contain elements of various types.

In [ ]:
# Exam
arr1 = np.array([[1],[2],[3]])
print(arr1.shape)
arr2 = np.array([1,2,3])
print(arr2.shape)
arr1*arr2

(3, 1)
(3,)


array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.shape)
print(arr.size)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
4


In [ ]:
l = [1,2,3,4]
print(l)
print(type(l))


[1, 2, 3, 4]
<class 'list'>


In [ ]:
l1 = [1,2,"python"]

In [ ]:
arr2 = np.array(l1)
print(arr2)
print(type(arr2))

['1' '2' 'python']
<class 'numpy.ndarray'>


In [ ]:
arr3 = np.array([[1,2],[3,4]])
print(arr3)
print(type(arr3))
print(arr3.size)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
4


In [ ]:
arr4 = np.array([[1,2],[3,4]],dtype=float)
print(arr4)
print(type(arr4))

[[1. 2.]
 [3. 4.]]
<class 'numpy.ndarray'>


In [ ]:
# It returns number of rows in tuples


In [ ]:
ar = np.array([[1,3],[4,5],[6,9]])
print(ar)
print(type(ar))
print(ar.shape)
print(ar.size)

[[1 3]
 [4 5]
 [6 9]]
<class 'numpy.ndarray'>
(3, 2)
6


In [ ]:
ar1 = np.array([[[1,3],[4,5],[6,9]]])
print(ar1)
print(type(ar1))
print(ar1.shape)
print(ar1.size)

[[[1 3]
  [4 5]
  [6 9]]]
<class 'numpy.ndarray'>
(1, 3, 2)
6


In [ ]:
ar2 = np.array([[[1,3],[4,5]],[6,9]])
print(ar2)
print(type(ar2))
print(ar2.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.

In [ ]:
a2 = np.array([[[1,3],[4,5]],[[6,9]]])
print(a2)
print(type(a2))
print(a2.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
a1 = np.array([[[1,3],[4,5]],[[6],[9]]])
print(a1)
print(type(a1))
print(a1.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.

In [ ]:
ar3 = np.array([[[1,3],[4,5]],[[6,9],[5,9]]])
print(ar3)
print(type(ar3))
print(ar3.shape)

[[[1 3]
  [4 5]]

 [[6 9]
  [5 9]]]
<class 'numpy.ndarray'>
(2, 2, 2)


In [ ]:
# Numpy array attributes
print(arr4)
print(arr4.shape)

[[1. 2.]
 [3. 4.]]
(2, 2)


In [ ]:
# Reshape function
arr5 = arr4.reshape(4,1)
print(arr5)

[[1.]
 [2.]
 [3.]
 [4.]]


In [ ]:
arrr = arr4.reshape(4,)
print(arrr)

[1. 2. 3. 4.]


In [ ]:
arr6 = arr4.reshape(2,3)
print(arr6)

ValueError: cannot reshape array of size 4 into shape (2,3)

In [ ]:
arr6 = arr4.reshape(1,4)
print(arr6)
print(arr6.shape)

[[1. 2. 3. 4.]]
(1, 4)


In [ ]:
# ndim - find the dimension of array

In [ ]:
print(arr4.ndim)

2


In [ ]:
print(arr6.ndim)

2


In [ ]:
arr7 = np.array([1,2,5,7])
print(arr7.ndim)

1


In [ ]:
# numpy size : Find the size of array

In [ ]:
print(arr7.size)

4


In [ ]:
print(arr4.size)

4


In [ ]:
# numpy arange method : create 1D array

In [ ]:
a = np.arange(5)
print(a)
print(a.ndim)
print(type(a))
print(a.shape)

[0 1 2 3 4]
1
<class 'numpy.ndarray'>
(5,)


In [ ]:
b = np.arange(2,10)
print(b)
print(b.ndim)
print(type(b))
print(b.shape)

[2 3 4 5 6 7 8 9]
1
<class 'numpy.ndarray'>
(8,)


In [ ]:
c = np.arange(2,20,2, dtype=float)
print(c)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [ ]:
d = np.arange(2,22,2, dtype=int).reshape(2,5)
print(d)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [ ]:
# Operation on array

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,9])
# Max value
print(a.max())

9


In [ ]:
print(a.min())

1


In [ ]:
print(a.sum())

15


In [ ]:
print(a.mean())

3.75


In [ ]:
print(a.std())

3.112474899497183


In [ ]:
no = np.arange(11)
print(no)
print(no.sum())


[ 0  1  2  3  4  5  6  7  8  9 10]
55


In [ ]:
arr1 = np.array([[1,5],[6,9]])
arr2 = np.array([[2,9],[8,9]])
print(arr1)
print(arr2)

[[1 5]
 [6 9]]
[[2 9]
 [8 9]]


In [ ]:
add = arr1 + arr2
print(add)

[[ 3 14]
 [14 18]]


In [ ]:
sub = arr1 - arr2
print(sub)

[[-1 -4]
 [-2  0]]


In [ ]:
mul = arr1 * arr2
print(mul)

[[ 2 45]
 [48 81]]


In [ ]:
div = arr1 / arr2
print(div)

[[0.5        0.55555556]
 [0.75       1.        ]]


In [ ]:
# Matrix operation

In [ ]:
mat1 = np.matrix(arr1)
print(mat1)
print(type(mat1))

[[1 5]
 [6 9]]
<class 'numpy.matrix'>


In [ ]:
mat2 = np.mat(arr2)
print(mat2)
print(type(mat2))

AttributeError: `np.mat` was removed in the NumPy 2.0 release. Use `np.asmatrix` instead.

In [ ]:
mat2 = np.matrix(arr2)
print(mat2)
print(type(mat2))

[[2 9]
 [8 9]]
<class 'numpy.matrix'>


In [ ]:
print(mat1 + mat2)

[[ 3 14]
 [14 18]]


In [ ]:
print(arr1 + arr2)

[[ 3 14]
 [14 18]]


In [ ]:
print(arr1 * arr2)

[[ 2 45]
 [48 81]]


In [ ]:
print(mat1 * mat2)

[[ 42  54]
 [ 84 135]]


In [ ]:
print(arr1.dot(arr2))

[[ 42  54]
 [ 84 135]]


In [ ]:
print(arr1 @ arr2)

[[ 42  54]
 [ 84 135]]


In [ ]:
print(mat1)
print(mat2)

[[1 5]
 [6 9]]
[[2 9]
 [8 9]]


In [ ]:
# Identity matrix

In [ ]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
I1 = np.eye(3, dtype=int)
print(I1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# Diagonal matrix

In [ ]:
D = np.diag([5,7,8,10])
print(D)
print(type(D))

[[ 5  0  0  0]
 [ 0  7  0  0]
 [ 0  0  8  0]
 [ 0  0  0 10]]
<class 'numpy.ndarray'>


In [ ]:
A1 = np.array([[1,2],[3,4]])
A2 = np.array([[3,4],[5,6]])
print(A1)
print(A2)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [ ]:
A3 =np.hstack((A1,A2))
print(A3)

[[1 2 3 4]
 [3 4 5 6]]


In [ ]:
A4 = np.vstack((A1,A2))
print(A4)

[[1 2]
 [3 4]
 [3 4]
 [5 6]]


In [ ]:
ar1 = np.array([1,2,3,5,6])
ar2 = np.array([2,3,6,7,1])


In [ ]:
# set operation

In [ ]:
inter = np.intersect1d(ar1,ar2)
print(inter)

[1 2 3 6]


In [ ]:
union = np.union1d(ar1,ar2)
print(union)
print(type(union))

[1 2 3 5 6 7]
<class 'numpy.ndarray'>


In [ ]:
# Difference in ar1 not in ar2
# op: [5]

In [ ]:
diff1 = np.setdiff1d(ar1,ar2)
print(diff1)

[5]


In [ ]:
# difference elements ar2 not from ar1
# op : [7]

In [ ]:
diff2 = np.setdiff1d(ar2,ar1)
print(diff2)

[7]


In [ ]:
# Symmetric difference
# op : [5,7]

In [ ]:
sym = np.setxor1d(ar1,ar2)
print(sym)

[5 7]


In [ ]:
concat = np.concatenate((ar1,ar2))
print(concat)

[1 2 3 5 6 2 3 6 7 1]


In [ ]:
concat2 = np.concat((ar1,ar2))
print(concat2)
print(type(concat2))

[1 2 3 5 6 2 3 6 7 1]
<class 'numpy.ndarray'>


In [ ]:
l = [1,4,5,6,8,99,1]
print(l.count(1))

2


In [ ]:
count1 = concat2.count(1)
print(count1)


AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [ ]:
count1 = list(concat2).count(1)
print(count1)


2


# Random number:
- Random number does not mean a different number everytime
- Random means something that cannot be predicted logically
- Ex: OTP, Password,Capcha
- Numpy offere random module to work with random
- There are two methods

In [ ]:
import numpy as np

In [ ]:
no = np.random.randint(100)
print(no)

44


In [ ]:
no1 = np.random.randint(100000)
print(no1)

53908


In [ ]:
no = np.random.randint(5000,10000)
print(no)

6824


In [ ]:
no5 = np.random.randint(399,400)
print(no5)

399


In [ ]:
no6 = np.random.randint(100,999,3)
print(no6)

[770 668 503]


- Random method take size parameter where you can specify the shape of array

In [ ]:
from numpy import random

In [ ]:
no2 = random.randint(10000, size=5)
print(no2)

[1400 7398 8800 2301 1399]


- rand() method returns random float between 0 to 1

In [ ]:
import numpy.random as npr

In [ ]:
no3 = npr.rand()
print(no3)

0.06314545812530614


In [ ]:
no9 = np.random.rand()
print(no9)

0.26953976040226535


In [ ]:
no6 = npr.rand(4)
print(no6)

[0.14276762 0.9346664  0.25512573 0.55711184]


In [ ]:
no4 = npr.random()
print(no4)

0.2582918148126725


In [ ]:
n = np.random.random()
print(n)

0.7415028519801437


In [ ]:
n1 = np.random()
print(n1)

TypeError: 'module' object is not callable

In [ ]:
no10= np.random.random(4)
print(no10)

[0.34474049 0.96718938 0.27155223 0.55402476]


In [ ]:
no5 = npr.random(4)
print(no5)

[0.97421306 0.97833026 0.31575562 0.85544652]


In [ ]:
no7 = npr.rand(4,2)
print(no7)

[[0.29005464 0.94170738]
 [0.75890505 0.40508018]
 [0.29007017 0.38549709]
 [0.46880026 0.05903375]]


In [ ]:
no9 = npr.random_integers(2,15)
print(no9)

13


<ipython-input-27-36550051a49d>:1: DeprecationWarning: This function is deprecated. Please call randint(2, 15 + 1) instead
  no9 = npr.random_integers(2,15)


In [ ]:
no8 = npr.random_integers(2,15,3)
print(no8)

[13 11 12]


<ipython-input-26-ba0ba7d95ae2>:1: DeprecationWarning: This function is deprecated. Please call randint(2, 15 + 1) instead
  no8 = npr.random_integers(2,15,3)


In [ ]:
no_choice = npr.choice([1,5,99,78,65,200])
print("Random choice from list: ",no_choice)

Random choice from list:  200


In [ ]:
no_choice = npr.choice([1,5,99,78,65,200])
print("Random choice from list: ",no_choice)

Random choice from list:  78


# Extra for reading

In [ ]:
import numpy as np

In [ ]:
n1 = np.array([1,2,3,4,5,6,7,8,9,10])
n2 = np.arange(15)
print(n1)
print(n2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
n3 = np.random.randint(10,20,5)
print(n3)


[13 18 16 10 17]


In [ ]:
n5 = np.random.randint(10,20,size=5)
print(n5)

[18 10 10 12 11]


In [ ]:
n6 = np.random.rand()
print(n6)
print(type(n6))

0.6501596906914561
<class 'float'>


In [ ]:
n = np.random.rand(1)
print(n)
print(type(n))

[0.34407031]
<class 'numpy.ndarray'>


In [ ]:
n7 = np.random.rand(5)
print(n7)

[0.73256392 0.16935489 0.35595672 0.50264682 0.12898343]


In [ ]:
n8 = np.random.rand(5,2)
print(n8)

[[0.69123883 0.74358769]
 [0.96285608 0.59809819]
 [0.16176136 0.76548926]
 [0.04555172 0.26956052]
 [0.13173746 0.66472702]]


In [ ]:
n = np.random.random()
print(n)

0.1967760149956772


In [ ]:
n9 = np.random.random(5)
print(n9)

[9.73337445e-01 4.39849445e-01 2.45428921e-04 5.03919180e-01
 2.65944122e-02]


In [ ]:
n10 = np.random.random(4)
print(n10)

[0.98394639 0.90464379 0.13984854 0.10220913]


# Extra for reading:

## Difference between range() and arange()

| Feature                 | `range()`               | `np.arange()`                  |
| ----------------------- | ----------------------- | ------------------------------ |
| **Library**             | Built-in                | NumPy                          |
| **Returns**             | `range` object          | `numpy.ndarray` (NumPy array)  |
| **Supports floats**     | ❌ No                    | ✅ Yes                          |
| **Memory-efficient**    | ✅ Yes (lazy evaluation) | ❌ No (generates full array)    |
| **Use in loops**        | ✅ Common                | 👎 Not typical                 |
| **Use in calculations** | 👎 Limited              | ✅ Ideal for numeric operations |


In [ ]:
for i in range(1, 10, 2):
    print(i)
# Output: 1, 3, 5, 7, 9


1
3
5
7
9


In [ ]:
import numpy as np

arr = np.arange(0, 5.5, 0.5)
print(arr)
# Output: [0.  0.5 1.  1.5 2.  ... 5.]


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [ ]:
l = list(range(5))
print(l)

[0, 1, 2, 3, 4]


In [ ]:
p = range(5)
print(p)

range(0, 5)


In [ ]:
ar1 = np.arange(0,5.5)
print(ar1)

[0. 1. 2. 3. 4. 5.]
